/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#fff0f4",
        "secondary-fixed": "#f7e7b4",
        "on-surface-variant": "#634250",
        "primary": "#d83a78",
        "tertiary-fixed-dim": "#cbc6b9",
        "surface-container-low": "#fff5f8",
        "on-secondary-fixed": "#3a2a00",
        "tertiary-container": "#302e25",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#3d041b",
        "error-container": "#ffdad6",
        "surface-variant": "#f4d6e1",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#851c45",
        "outline": "#997382",
        "tertiary-fixed": "#e8e2d4",
        "surface-tint": "#d83a78",
        "on-tertiary-container": "#9a9589",
        "error": "#ba1a1a",
        "surface-container-high": "#fce4ed",
        "surface": "#fff0f4",
        "on-background": "#3a1523",
        "on-primary-container": "#ffd9e4",
        "outline-variant": "#e5c4d0",
        "tertiary": "#1b1a11",
        "on-surface": "#3a1523",
        "background": "#fff0f4",
        "primary-fixed-dim": "#ffb1ca",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#49473d",
        "inverse-surface": "#382d32",
        "inverse-primary": "#ffb1ca",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#f4d6e1",
        "primary-fixed": "#ffd9e4",
        "surface-dim": "#f7d8e4",
        "secondary-fixed-dim": "#e9c349",
        "on-tertiary-fixed": "#1d1c13",
        "on-secondary-container": "#5e480e",
        "secondary": "#8b6f20",
        "primary-container": "#ab1e56",
        "secondary-container": "#fed65b",
        "surface-bright": "#fff0f4",
        "surface-container": "#f8e2eb",
        "gold-border": "#c5a059",
        "gold-metallic": "#d4af37",
        "pink-canvas": "#ff5e97"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "sm": "12px",
        "gutter": "16px",
        "xl": "32px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        "lg": "24px",
        "xs": "4px",
        "base": "8px"
      },
      fontFamily: {
        "sans": ["Be Vietnam Pro", "Sarabun", "sans-serif"],
        "headline-sm": ["Be Vietnam Pro", "Sarabun"],
        "label-lg": ["Be Vietnam Pro", "Sarabun"],
        "headline-lg-mobile": ["Be Vietnam Pro", "Sarabun"],
        "body-lg": ["Be Vietnam Pro", "Sarabun"],
        "headline-lg": ["Be Vietnam Pro", "Sarabun"],
        "headline-md": ["Be Vietnam Pro", "Sarabun"],
        "label-sm": ["Be Vietnam Pro", "Sarabun"],
        "body-md": ["Be Vietnam Pro", "Sarabun"]
      },
      fontSize: {
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1px", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
